<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EPRUSARW1003" name="tests.mainPageTests.portfolioPageTests.AddFileInPortfolioTest" tests="4" failures="1" timestamp="31 May 2018 09:36:38 GMT" time="80.637" errors="0">
  <testcase name="addFileAndSafeWithInvalidFile" time="7.566" classname="tests.mainPageTests.portfolioPageTests.AddFileInPortfolioTest">
    <failure type="java.lang.AssertionError" message="Invalid file was safe on page of Common portfolio expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Invalid file was safe on page of Common portfolio expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at tests.mainPageTests.portfolioPageTests.AddFileInPortfolioTest.addFileAndSafeWithInvalidFile(AddFileInPortfolioTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at runner.Runner.run(Runner.java:49)
	at runner.Runner.main(Runner.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- addFileAndSafeWithInvalidFile -->
  <testcase name="addFileAndSafeWithInvalidFile" time="48.134" classname="tests.mainPageTests.portfolioPageTests.AddFileInPortfolioTest"/>
  <testcase name="addFileAndSafe" time="7.480" classname="tests.mainPageTests.portfolioPageTests.AddFileInPortfolioTest"/>
  <testcase name="addFileAndSafeWithInvalidFile" time="17.457" classname="tests.mainPageTests.portfolioPageTests.AddFileInPortfolioTest"/>
</testsuite> <!-- tests.mainPageTests.portfolioPageTests.AddFileInPortfolioTest -->
